global:
scrape_interval:     15s  # By default, scrape targets every 15 seconds.
evaluation_interval: 15s  # By default, scrape targets every 15 seconds.
# scrape_timeout is set to the global default value (10s).
external_labels:
    cluster: 'test-cluster'
    monitor: "prometheus"

scrape_configs:
  - job_name: 'overwritten-nodes'
      honor_labels: true  # Do not overwrite job & instance labels.
      static_configs:
      - targets:
      - '192.168.16.115:9100'
      - '192.168.16.116:9100'
      - '192.168.16.117:9100'
      - '192.168.16.118:9100'
      - '192.168.16.119:9100'
      - '192.168.16.120:9100'

  - job_name: 'tidb'
      honor_labels: true  # Do not overwrite job & instance labels.
      static_configs:
      - targets:
      - '192.168.16.115:10080'
  - job_name: 'pd'
      honor_labels: true  # Do not overwrite job & instance labels.
      static_configs:
      - targets:
      - '192.168.16.115:2379'
      - '192.168.16.116:2379'
      - '192.168.16.117:2379'

  - job_name: 'tikv'
      honor_labels: true  # Do not overwrite job & instance labels.
      static_configs:
      - targets:
      - '192.168.16.118:20180'
      - '192.168.16.119:20180'
      - '192.168.16.120:20180'